### PR TITLE
Small adjustment in Network Manager wording for ADR-0014

### LINKED ISSUE #403: ADR 14 - NetworkManager not to be actively used
## Context

ADR 14 states that

"NetworkManager is installed but not actively used."

Some add-ons (AdGuard for one) requires a fixed IP. As far as I am aware, the only way to achieve that is via NetworkManager.

It is also at odds with this documentation.

https://github.com/home-assistant/operating-system/blob/dev/Documentation/network.md#static-ip

## Proposal

The restriction is modified to be that "NetworkManager is installed but not actively used other than to set a Fixed IP & Gateway and Static DNS."

## Consequences

Honestly, I don't know, I just know that the install instructions for the add-on are now contradicted by the ADR.

### PR DESCRIPTION
**Pull request by frenck**
- Small wording change on the use of the NetworkManager, fixes #403
- Adjusted list char used to make it consistent with the rest of the document

### CODE REVIEW

**Comment by pvizeli** [comment]
That's wrong. NetworkManager is force required and need active used for an support system. I'm fine to change that if someone will add systemd networkd support too

**Comment by frenck** [comment]
Yeah @pvizeli, that is what I tried to re-word it too. I see the confusion caused by this one as well.
Adjusting.

**Comment by frenck** [comment]
@pvizeli Made a small tweak to make it more clear? Is this acceptable?

**Comment by pvizeli** [comment]
Yeah I think that is fine :)

**Pull request merged**
